In [1]:
import numpy as np

In [12]:
h = [30,28,5,8,9]
h

[30, 28, 5, 8, 9]

In [13]:
for i in range(len(h)):
    h[i] += 7
h

[37, 35, 12, 15, 16]

In [14]:
d = []
for i in h:
    d.append(i+7)
d

[44, 42, 19, 22, 23]

In [15]:
s = (6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [34]:
#tuples are immutable 
s*3

(36, 4, 9, 81, 49, 25, 64, 36, 4, 9, 81, 49, 25, 64, 36, 4, 9, 81, 49, 25, 64)

In [16]:
list(s)

[6, 2, 3, 9, 7, 5, 8]

In [19]:
k = []
for i in s:
    k.append(i**2)
k

[36, 4, 9, 81, 49, 25, 64]

In [20]:
tuple(k)

(36, 4, 9, 81, 49, 25, 64)

In [22]:
y = list(s)
k = []
for i in y:
    k.append(i**2)
s=tuple(k)
s

(36, 4, 9, 81, 49, 25, 64)

In [23]:
l = []
for i in s:
    if i>50:
        l.append(i)
l

[81, 64]

In [38]:
arr=np.array([20,50,30,70,80,40,36,54,23,98])
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [44]:
arr + 7

array([ 41,  71,  51,  91, 101,  61,  57,  75,  44, 119])

In [43]:
for i in range(len(arr)):
    arr[i] += 7
arr

array([ 34,  64,  44,  84,  94,  54,  50,  68,  37, 112])

In [45]:
arr*5

array([170, 320, 220, 420, 470, 270, 250, 340, 185, 560])

In [46]:
arr%4

array([2, 0, 0, 0, 2, 2, 2, 0, 1, 0], dtype=int32)

In [47]:
arr[4:8]

array([94, 54, 50, 68])

In [52]:
arr[2:5:2]

array([44, 94])

In [53]:
arr[arr<=50]

array([34, 44, 50, 37])

In [54]:
k = [36,4,9,81,49,25,64]
k

[36, 4, 9, 81, 49, 25, 64]

In [55]:
index =[]
for i in range(len(k)):
    if k[i]>20:
        index.append(i)
index
        

[0, 3, 4, 5, 6]

In [56]:
index =[]
for i in range(len(k)):
    if k[i]>50:
        index.append(i)
index
        

[3, 6]